# Generated by Django 2.0.6 on 2020-04-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_book_android', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
